//===--- UnicodeOperatorCharSets.h - U1 user-operator code points ---------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
///
/// \file
/// GENERATED FILE - DO NOT EDIT.
///
/// The frozen U1 set of Unicode user-defined operator code points, plus the
/// table of named exclusions and the reason each was kept out.
///
/// Generated by, from a directory holding the five UCD 17.0.0 data files
/// (PropList.txt, DerivedAge.txt, UnicodeData.txt, DerivedCoreProperties.txt,
/// emoji/emoji-data.txt) fetched from
/// https://www.unicode.org/Public/17.0.0/ucd/ :
///
///   python3 docs/pattern-syntax-audit.py <ucd-dir> --emit-header \
///       > clang/lib/Lex/UnicodeOperatorCharSets.h
///
/// The generator lives in the plan repo, not in LLVM. UCD version 17.0.0,
/// DerivedAge.txt dated 2025-07-30.
///
/// Derivation (unicode-operators.md U#5, predicates 1-5): Pattern_Syntax, and
/// non-ASCII, and inside the mathematical/arrow blocks (U+2190-21FF,
/// U+2200-22FF, U+2300-23FF, U+27C0-27EF, U+27F0-27FF, U+2900-297F,
/// U+2980-29FF, U+2A00-2AFF, U+2B00-2BFF), and General_Category Sm or So,
/// minus the named exclusions below. The predicates are *derivation inputs*
/// applied once, offline: U1 freezes the resulting enumeration at UCD
/// 17.0.0 by fiat, so this table does not track later UCD versions.
///
/// Result: 1381 code points in 32 contiguous ranges, 256 bytes.
///
//===----------------------------------------------------------------------===//

#ifndef LLVM_CLANG_LIB_LEX_UNICODEOPERATORCHARSETS_H
#define LLVM_CLANG_LIB_LEX_UNICODEOPERATORCHARSETS_H

#include "llvm/Support/UnicodeCharRanges.h"
#include <cstdint>

namespace clang {

/// The frozen U1 user-operator set, UCD 17.0.0: 1381 code points in
/// 32 ranges, sorted and non-overlapping as llvm::sys::UnicodeCharSet
/// requires.
static const llvm::sys::UnicodeCharRange UserOperatorRanges[] = {
    {0x2190, 0x21CF},   {0x21D1, 0x21D1},   {0x21D3, 0x21D3},
    {0x21D5, 0x2201},   {0x2203, 0x2206},   {0x2208, 0x2211},
    {0x2213, 0x2214},   {0x2216, 0x2216},   {0x2218, 0x2218},
    {0x221A, 0x221D},   {0x221F, 0x2222},   {0x2224, 0x2235},
    {0x2237, 0x2263},   {0x2266, 0x22C4},   {0x22C6, 0x2307},
    {0x230C, 0x2319},   {0x231C, 0x2328},   {0x232B, 0x23E8},
    {0x23ED, 0x23EF},   {0x23F1, 0x23F2},   {0x23F4, 0x23FF},
    {0x27C0, 0x27C4},   {0x27C7, 0x27E5},   {0x27F0, 0x27FF},
    {0x2900, 0x2982},   {0x2999, 0x29D7},   {0x29DC, 0x29FB},
    {0x29FE, 0x2B1A},   {0x2B1D, 0x2B4F},   {0x2B51, 0x2B54},
    {0x2B56, 0x2B73},   {0x2B76, 0x2BFF},
};

/// Why a code point that a reader might expect to be a user operator is
/// not one. U05 turns these into diagnostics; the exclusions exist for the
/// reader's protection, so the diagnostics should say so.
enum class UserOperatorExclusionReason {
  /// Not a named exclusion (it simply fails one of predicates 1-4, or is
  /// a member of the set).
  None,
  /// TR31 7.1's mathematical notation profile earmarks it as an
  /// *identifier* character: it names things, it does not combine them.
  /// Clang already admits these as identifiers; see
  /// MathematicalNotationProfileIDStartRanges in UnicodeCharSets.h.
  IdentifierProfile,
  /// UTS #39 confusable with an existing C++ token. Rejected outright,
  /// never aliased: something that looks like `-` but is not must fail to
  /// lex rather than quietly mean something else.
  ConfusableWith,
  /// TR31 7.2's emoji profile carve-out.
  EmojiPresentation,
};

struct UserOperatorExclusion {
  uint32_t CodePoint;
  UserOperatorExclusionReason Reason;
  /// For ConfusableWith, the existing token this code point apes;
  /// nullptr otherwise.
  const char *Confusable;
};

/// The named exclusions of U#5 predicate 5 (16 of them) plus the
/// 12 emoji-presentation code points inside the U1 blocks. Sorted by
/// code point.
static const UserOperatorExclusion ExcludedOperatorChars[] = {
    // ⁄ U+2044 FRACTION SLASH
    {0x2044, UserOperatorExclusionReason::ConfusableWith, "/"},
    // ⇐ U+21D0 LEFTWARDS DOUBLE ARROW
    {0x21D0, UserOperatorExclusionReason::ConfusableWith, "<="},
    // ⇒ U+21D2 RIGHTWARDS DOUBLE ARROW
    {0x21D2, UserOperatorExclusionReason::ConfusableWith, "=>"},
    // ⇔ U+21D4 LEFT RIGHT DOUBLE ARROW
    {0x21D4, UserOperatorExclusionReason::ConfusableWith, "<=>"},
    // ∂ U+2202 PARTIAL DIFFERENTIAL
    {0x2202, UserOperatorExclusionReason::IdentifierProfile, nullptr},
    // ∇ U+2207 NABLA
    {0x2207, UserOperatorExclusionReason::IdentifierProfile, nullptr},
    // − U+2212 MINUS SIGN
    {0x2212, UserOperatorExclusionReason::ConfusableWith, "-"},
    // ∕ U+2215 DIVISION SLASH
    {0x2215, UserOperatorExclusionReason::ConfusableWith, "/"},
    // ∗ U+2217 ASTERISK OPERATOR
    {0x2217, UserOperatorExclusionReason::ConfusableWith, "*"},
    // ∙ U+2219 BULLET OPERATOR
    {0x2219, UserOperatorExclusionReason::ConfusableWith, "."},
    // ∞ U+221E INFINITY
    {0x221E, UserOperatorExclusionReason::IdentifierProfile, nullptr},
    // ∣ U+2223 DIVIDES
    {0x2223, UserOperatorExclusionReason::ConfusableWith, "|"},
    // ∶ U+2236 RATIO
    {0x2236, UserOperatorExclusionReason::ConfusableWith, ":"},
    // ≤ U+2264 LESS-THAN OR EQUAL TO
    {0x2264, UserOperatorExclusionReason::ConfusableWith, "<="},
    // ≥ U+2265 GREATER-THAN OR EQUAL TO
    {0x2265, UserOperatorExclusionReason::ConfusableWith, ">="},
    // ⋅ U+22C5 DOT OPERATOR
    {0x22C5, UserOperatorExclusionReason::ConfusableWith, "."},
    // ⌚ U+231A WATCH
    {0x231A, UserOperatorExclusionReason::EmojiPresentation, nullptr},
    // ⌛ U+231B HOURGLASS
    {0x231B, UserOperatorExclusionReason::EmojiPresentation, nullptr},
    // ⏩ U+23E9 BLACK RIGHT-POINTING DOUBLE TRIANGLE
    {0x23E9, UserOperatorExclusionReason::EmojiPresentation, nullptr},
    // ⏪ U+23EA BLACK LEFT-POINTING DOUBLE TRIANGLE
    {0x23EA, UserOperatorExclusionReason::EmojiPresentation, nullptr},
    // ⏫ U+23EB BLACK UP-POINTING DOUBLE TRIANGLE
    {0x23EB, UserOperatorExclusionReason::EmojiPresentation, nullptr},
    // ⏬ U+23EC BLACK DOWN-POINTING DOUBLE TRIANGLE
    {0x23EC, UserOperatorExclusionReason::EmojiPresentation, nullptr},
    // ⏰ U+23F0 ALARM CLOCK
    {0x23F0, UserOperatorExclusionReason::EmojiPresentation, nullptr},
    // ⏳ U+23F3 HOURGLASS WITH FLOWING SAND
    {0x23F3, UserOperatorExclusionReason::EmojiPresentation, nullptr},
    // ⬛ U+2B1B BLACK LARGE SQUARE
    {0x2B1B, UserOperatorExclusionReason::EmojiPresentation, nullptr},
    // ⬜ U+2B1C WHITE LARGE SQUARE
    {0x2B1C, UserOperatorExclusionReason::EmojiPresentation, nullptr},
    // ⭐ U+2B50 WHITE MEDIUM STAR
    {0x2B50, UserOperatorExclusionReason::EmojiPresentation, nullptr},
    // ⭕ U+2B55 HEAVY LARGE CIRCLE
    {0x2B55, UserOperatorExclusionReason::EmojiPresentation, nullptr},
};

/// True if \p C is a member of the frozen U1 user-operator set.
static inline bool isUserOperatorChar(uint32_t C) {
  static const llvm::sys::UnicodeCharSet UserOperatorChars(UserOperatorRanges);
  return UserOperatorChars.contains(C);
}

/// The exclusion table entry for \p C, or nullptr if \p C is not a named
/// exclusion. Table is tiny (a linear scan beats a binary search here) and
/// sorted, so the scan can stop early.
static inline const UserOperatorExclusion *
getUserOperatorExclusion(uint32_t C) {
  for (const UserOperatorExclusion &E : ExcludedOperatorChars) {
    if (E.CodePoint == C)
      return &E;
    if (E.CodePoint > C)
      break;
  }
  return nullptr;
}

/// Why \p C is not a user operator, when there is a named reason to give.
static inline UserOperatorExclusionReason getExclusionReason(uint32_t C) {
  if (const UserOperatorExclusion *E = getUserOperatorExclusion(C))
    return E->Reason;
  return UserOperatorExclusionReason::None;
}

} // namespace clang

#endif // LLVM_CLANG_LIB_LEX_UNICODEOPERATORCHARSETS_H
